// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// Super Hero
export const SUPERHERO_REQUEST = 'SUPERHERO_REQUEST';
export const SUPERHERO_RESPONSE = 'SUPERHERO_RESPONSE';
export const SUPERHERO_FAILED = 'SUPERHERO_FAILED';

export const SUPERHERO_SEARCH_REQUEST = 'SUPERHERO_SEARCH_REQUEST';
export const SUPERHERO_SEARCH_RESPONSE = 'SUPERHERO_SEARCH_RESPONSE';
export const SUPERHERO_SEARCH_FAILED = 'SUPERHERO_SEARCH_FAILED';
